### ISSUE TITLE
Problem in running code

### ISSUE THREAD

**Issue by itoshi-sae5** [AbdelrahmanBayoumi/HotelFX#2]
Whenever i try to run your your code it shows a window of available classes and it is empty why?
![image](https://github.com/AbdelrahmanBayoumi/HotelFX/assets/146688706/a22c18c6-e04e-4339-a5df-57fc08682b4c)
Like this
Can you help me?

**Comment by AbdelrahmanBayoumi** [comment]
Hi @itoshi-sae5,
This issue often arises due to version mismatches. This project was originally developed using Oracle's Java version 8. It's possible you might be running it with a newer Java version. Please ensure you're using the specified requirements, as mentioned here: https://github.com/AbdelrahmanBayoumi/HotelFX#requirements.

Make sure you've also started the SQL server with XAMPP, following the instructions here: https://github.com/AbdelrahmanBayoumi/HotelFX#how-to-run.

To run the project, navigate to the `Project.java` file (located under the `project` package in `src`). Right-click within the file and select 'Run File'. Let me know if this resolves your issue!
![image](https://github.com/AbdelrahmanBayoumi/HotelFX/assets/48678280/67164717-29cb-48fa-864b-d40fdf8973e9)

**Comment by itoshi-sae5** [comment]
What is the username and password for login?
